// Code generated by protoc-gen-go.
// source: inventory.proto
// DO NOT EDIT!

/*
Package inventoryapiv1 is a generated protocol buffer package.

It is generated from these files:
	inventory.proto

It has these top-level messages:
	Email
	CreateEmailRequest
	FindEmailRequest
	FindEmailResponse
*/
package inventoryapiv1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Email struct {
	Recipient string `protobuf:"bytes,1,opt,name=recipient" json:"recipient,omitempty"`
	Subject   string `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *Email) Reset()                    { *m = Email{} }
func (m *Email) String() string            { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()               {}
func (*Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Email) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateEmailRequest struct {
	Recipient string `protobuf:"bytes,1,opt,name=recipient" json:"recipient,omitempty"`
	Subject   string `protobuf:"bytes,2,opt,name=subject" json:"subject,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *CreateEmailRequest) Reset()                    { *m = CreateEmailRequest{} }
func (m *CreateEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateEmailRequest) ProtoMessage()               {}
func (*CreateEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateEmailRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *CreateEmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *CreateEmailRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type FindEmailRequest struct {
	Recipient string `protobuf:"bytes,1,opt,name=recipient" json:"recipient,omitempty"`
}

func (m *FindEmailRequest) Reset()                    { *m = FindEmailRequest{} }
func (m *FindEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*FindEmailRequest) ProtoMessage()               {}
func (*FindEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FindEmailRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type FindEmailResponse struct {
	Emial *Email `protobuf:"bytes,1,opt,name=emial" json:"emial,omitempty"`
}

func (m *FindEmailResponse) Reset()                    { *m = FindEmailResponse{} }
func (m *FindEmailResponse) String() string            { return proto.CompactTextString(m) }
func (*FindEmailResponse) ProtoMessage()               {}
func (*FindEmailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FindEmailResponse) GetEmial() *Email {
	if m != nil {
		return m.Emial
	}
	return nil
}

func init() {
	proto.RegisterType((*Email)(nil), "inventoryapiv1.Email")
	proto.RegisterType((*CreateEmailRequest)(nil), "inventoryapiv1.CreateEmailRequest")
	proto.RegisterType((*FindEmailRequest)(nil), "inventoryapiv1.FindEmailRequest")
	proto.RegisterType((*FindEmailResponse)(nil), "inventoryapiv1.FindEmailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EmailInventoryService service

type EmailInventoryServiceClient interface {
	CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	FindEmail(ctx context.Context, in *FindEmailRequest, opts ...grpc.CallOption) (*FindEmailResponse, error)
}

type emailInventoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmailInventoryServiceClient(cc *grpc.ClientConn) EmailInventoryServiceClient {
	return &emailInventoryServiceClient{cc}
}

func (c *emailInventoryServiceClient) CreateEmail(ctx context.Context, in *CreateEmailRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/inventoryapiv1.EmailInventoryService/CreateEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailInventoryServiceClient) FindEmail(ctx context.Context, in *FindEmailRequest, opts ...grpc.CallOption) (*FindEmailResponse, error) {
	out := new(FindEmailResponse)
	err := grpc.Invoke(ctx, "/inventoryapiv1.EmailInventoryService/FindEmail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EmailInventoryService service

type EmailInventoryServiceServer interface {
	CreateEmail(context.Context, *CreateEmailRequest) (*google_protobuf.Empty, error)
	FindEmail(context.Context, *FindEmailRequest) (*FindEmailResponse, error)
}

func RegisterEmailInventoryServiceServer(s *grpc.Server, srv EmailInventoryServiceServer) {
	s.RegisterService(&_EmailInventoryService_serviceDesc, srv)
}

func _EmailInventoryService_CreateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailInventoryServiceServer).CreateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventoryapiv1.EmailInventoryService/CreateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailInventoryServiceServer).CreateEmail(ctx, req.(*CreateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailInventoryService_FindEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailInventoryServiceServer).FindEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/inventoryapiv1.EmailInventoryService/FindEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailInventoryServiceServer).FindEmail(ctx, req.(*FindEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmailInventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "inventoryapiv1.EmailInventoryService",
	HandlerType: (*EmailInventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmail",
			Handler:    _EmailInventoryService_CreateEmail_Handler,
		},
		{
			MethodName: "FindEmail",
			Handler:    _EmailInventoryService_FindEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}

func init() { proto.RegisterFile("inventory.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x1b, 0xa5, 0x4a, 0xa6, 0xe0, 0x9f, 0x81, 0x4a, 0x88, 0x1e, 0xea, 0x9e, 0x04, 0x61,
	0xab, 0xf5, 0x05, 0x04, 0xa9, 0x20, 0xde, 0xe2, 0xc9, 0x63, 0x12, 0xa7, 0x65, 0x25, 0xd9, 0x5d,
	0x37, 0x9b, 0x80, 0x6f, 0xe6, 0xe3, 0x49, 0x76, 0x9b, 0x1a, 0x23, 0x88, 0x17, 0x8f, 0x3b, 0xdf,
	0x6f, 0xe6, 0xdb, 0x99, 0x0f, 0x0e, 0x85, 0x6c, 0x48, 0x5a, 0x65, 0xde, 0xb9, 0x36, 0xca, 0x2a,
	0x3c, 0xd8, 0x16, 0x52, 0x2d, 0x9a, 0xeb, 0xf8, 0x74, 0xad, 0xd4, 0xba, 0xa0, 0xb9, 0x53, 0xb3,
	0x7a, 0x35, 0xa7, 0x52, 0xdb, 0x0d, 0xcc, 0x9e, 0x61, 0xbc, 0x2c, 0x53, 0x51, 0xe0, 0x19, 0x84,
	0x86, 0x72, 0xa1, 0x05, 0x49, 0x1b, 0x05, 0xb3, 0xe0, 0x22, 0x4c, 0xbe, 0x0a, 0x18, 0xc1, 0x7e,
	0x55, 0x67, 0xaf, 0x94, 0xdb, 0x68, 0xc7, 0x69, 0xdd, 0xb3, 0x55, 0x72, 0x25, 0x6d, 0xdb, 0xb5,
	0xeb, 0x95, 0xcd, 0x93, 0xad, 0x00, 0xef, 0x0c, 0xa5, 0x96, 0x9c, 0x41, 0x42, 0x6f, 0x35, 0x55,
	0xf6, 0x1f, 0x7c, 0xae, 0xe0, 0xe8, 0x5e, 0xc8, 0x97, 0xbf, 0xbb, 0xb0, 0x5b, 0x38, 0xee, 0x75,
	0x54, 0x5a, 0xc9, 0x8a, 0xf0, 0x12, 0xc6, 0x54, 0x8a, 0xb4, 0x70, 0xf8, 0x64, 0x31, 0xe5, 0xdf,
	0xcf, 0xc8, 0x3d, 0xed, 0x99, 0xc5, 0x47, 0x00, 0x53, 0x57, 0x78, 0xe8, 0xa0, 0x27, 0x32, 0x8d,
	0xc8, 0x09, 0x1f, 0x61, 0xd2, 0xdb, 0x1a, 0xd9, 0x70, 0xcc, 0xcf, 0x93, 0xc4, 0x27, 0xdc, 0x27,
	0xc4, 0xbb, 0x84, 0xf8, 0xb2, 0x4d, 0x88, 0x8d, 0x30, 0x81, 0x70, 0xfb, 0x51, 0x9c, 0x0d, 0x47,
	0x0d, 0xb7, 0x8e, 0xcf, 0x7f, 0x21, 0xfc, 0x96, 0x6c, 0x94, 0xed, 0x39, 0x97, 0x9b, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x07, 0xdc, 0xb4, 0x38, 0x02, 0x00, 0x00,
}
