<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto

namespace Inventoryapiv1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>inventoryapiv1.Email</code>
 */
class Email extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string recipient = 1;</code>
     */
    private $recipient = '';
    /**
     * <code>string subject = 2;</code>
     */
    private $subject = '';
    /**
     * <code>string content = 3;</code>
     */
    private $content = '';

    public function __construct() {
        \GPBMetadata\Inventory::initOnce();
        parent::__construct();
    }

    /**
     * <code>string recipient = 1;</code>
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * <code>string recipient = 1;</code>
     */
    public function setRecipient($var)
    {
        GPBUtil::checkString($var, True);
        $this->recipient = $var;
    }

    /**
     * <code>string subject = 2;</code>
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * <code>string subject = 2;</code>
     */
    public function setSubject($var)
    {
        GPBUtil::checkString($var, True);
        $this->subject = $var;
    }

    /**
     * <code>string content = 3;</code>
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * <code>string content = 3;</code>
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->content = $var;
    }

}

