<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto

namespace Inventoryapiv1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>inventoryapiv1.FindEmailResponse</code>
 */
class FindEmailResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.inventoryapiv1.Email emial = 1;</code>
     */
    private $emial = null;

    public function __construct() {
        \GPBMetadata\Inventory::initOnce();
        parent::__construct();
    }

    /**
     * <code>.inventoryapiv1.Email emial = 1;</code>
     */
    public function getEmial()
    {
        return $this->emial;
    }

    /**
     * <code>.inventoryapiv1.Email emial = 1;</code>
     */
    public function setEmial(&$var)
    {
        GPBUtil::checkMessage($var, \Inventoryapiv1\Email::class);
        $this->emial = $var;
    }

}

