<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto

namespace Inventoryapiv1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>inventoryapiv1.FindEmailRequest</code>
 */
class FindEmailRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string recipient = 1;</code>
     */
    private $recipient = '';

    public function __construct() {
        \GPBMetadata\Inventory::initOnce();
        parent::__construct();
    }

    /**
     * <code>string recipient = 1;</code>
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     * <code>string recipient = 1;</code>
     */
    public function setRecipient($var)
    {
        GPBUtil::checkString($var, True);
        $this->recipient = $var;
    }

}

